from setuptools import setup, find_packages  
setup(name = 'nodeModel', packages = find_packages())
setup(name='publicContractModel', packages=find_packages())
setup(name='nodeController', packages=find_packages())
setup(name='publicContractController', packages=find_packages())
setup(name = 'keyGenerationController', packages = find_packages())
setup(name = 'segmentation', packages = find_packages())
setup(name = 'normalization', packages = find_packages())
setup(name = 'gabor_filter', packages = find_packages())
setup(name = 'frequency', packages = find_packages())
setup(name = 'orientation', packages = find_packages())
setup(name = 'skeletonize', packages = find_packages())
setup(name = 'Chaff_Points_Generator', packages = find_packages())
setup(name='Constants', packages=find_packages())
setup(name='Geometric_Hashing_Transformer', packages=find_packages())
setup(name='Minutia_Converter', packages=find_packages())
setup(name = 'Minutia', packages = find_packages())
setup(name = 'Minutiae_Extractor', packages = find_packages())
setup(name = 'Polynomial_Extractor', packages = find_packages())
setup(name = 'Polynomial_Generator', packages = find_packages())
setup(name = 'Secret_generator', packages = find_packages())
setup(name = 'Strings', packages = find_packages())
setup(name = 'Vault_Verifier', packages = find_packages())
setup(name = 'Vault', packages = find_packages())
setup(name = 'symmetricEncryption', packages = find_packages())

setup(name = 'otp_controller', packages = find_packages())
setup(name = 'email_controller', packages = find_packages())
setup(name = 'fvss_controller', packages = find_packages())

setup(name='nodeAPI', packages=find_packages())